version: '3.7'

services:

  nginx:
    image: nginx:alpine
    ports:
     - "8080:8080"
     - "80:80"
    volumes:
     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
     - ./services/api:/var/www/vhosts/api
    working_dir: /var/www/vhosts/app
    depends_on:
      - "api"

  api:
     build: docker/api
     ports:
       - "9000:9000"
     volumes:
       - ./services/api:/var/www/vhosts/api
       - ./bin/migrations:/usr/local/bin/migrations
     working_dir: /var/www/vhosts/app
     environment:
       - ENV=development
       - API_KEY=49667D4B53178C27836C56A19EA38
       - RABBIT_HOST=rabbit
       - RABBIT_PORT=5672
       - RABBIT_USER=guest
       - RABBIT_PASSWORD=guest
     depends_on:
       - rabbit

  allocation-service:
     build: services/allocation
     environment:
       - MICRO_REGISTRY_ADDRESS=consul:8500
       - MICRO_BROKER_ADDRESS=amqp://guest:guest@rabbit:5672/
       - MICRO_BROKER=rabbitmq
     depends_on:
       - consul
       - rabbit

  db:
     image: postgres:10.2-alpine
     restart: always
     ports:
       - "5432:5432"
     volumes:
       - gymshark-data:/var/lib/postgresql/data
       - ./docker/postgresql:/docker-entrypoint-initdb.d
     environment:
       POSTGRES_USER: 'gymshark'
       POSTGRES_PASSWORD: password
       POSTGRES_DB: 'gymshark'

  rabbit:
     image: rabbitmq:3-management
     ports:
       - "8081:15672"

  consul:
     image: progrium/consul:latest
     command: -server -bootstrap -rejoin
     ports:
       - "8500"

volumes:
    gymshark-data: {}
