// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package config

import (
	"github.com/gileslloyd/gs-allocation-service/internal/app/controller"
	"github.com/gileslloyd/gs-allocation-service/internal/domain/allocation"
	"github.com/gileslloyd/gs-allocation-service/pkg/infrastructure/delivery/rpc"
	"github.com/gileslloyd/gs-allocation-service/pkg/infrastructure/microrepo"
)

// Injectors from container.go:

func CreateAllocationController() controller.Allocation {
	repository := microrepo.NewMicroPackRepo()
	rule := allocation.NewPackAllocationRule()
	service := allocation.NewAllocationService(repository, rule)
	controllerAllocation := controller.NewAllocationController(service)
	return controllerAllocation
}

func CreateMessageListener() rpc.MessageListener {
	v := GetRoutes()
	handler := rpc.NewHandler(v)
	messageListener := rpc.NewMessageListener(handler)
	return messageListener
}
